export {default as SectionProject} from './Projects/index'
export {default as SectionHero} from './Hero/index'
export {default as SectionSkills} from './Skills/index'
export {default as SectionAboutMe} from './About/index'
export {default as SectionContacts} from './Contacts/index'